### ISSUE TITLE
Conflito entre script `requirements.py` e `make publish` no github actions

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/cookiecutter-datapackage#23]
No nosso workflow do github actions o `make publish` é [executado dentro do runner do Github Actions](https://github.com/splor-mg/cookiecutter-datapackage/blob/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/.github/workflows/all.yaml#L32-L36), e não dentro do nosso container que possui as dependências python. Vide https://github.com/splor-mg/ppag-planejamento-dados/issues/30 para o histórico dessa decisão.

Isso faz com que [scripts/requirements.py](https://github.com/splor-mg/cookiecutter-datapackage/blob/c344282b80512c4dc1c5ad20fee1f34108aa6567/%7B%7B%20cookiecutter.project_slug%20%7D%7D/scripts/requirements.py) gere o seu erro usual durante a execução do [workflow](https://github.com/splor-mg/armazem-siafi-dados-2024/actions/runs/7130324547/job/19416428933):

```
git config user.name "Automated"
  git config user.email "actions@users.noreply.github.com"
  make publish
  shell: /usr/bin/bash -e {0}
Traceback (most recent call last):
  File "/home/runner/work/armazem-siafi-dados-2024/armazem-siafi-dados-2024/main.py", line 1, in <module>
    from frictionless import Package
ModuleNotFoundError: No module named 'frictionless'
Checking python packages...
202[3](https://github.com/splor-mg/armazem-siafi-dados-2024/actions/runs/7130324547/job/19416428933#step:7:3)-12-07T15:3[4](https://github.com/splor-mg/armazem-siafi-dados-2024/actions/runs/7130324547/job/19416428933#step:7:4):10+0000 WARNI [__main__] Required packages are missing: pip-tools, frictionless, dpm
Traceback (most recent call last):
  File "/home/runner/work/armazem-siafi-dados-2024/armazem-siafi-dados-2024/scripts/requirements.py", line 72, in <module>
    check_requirements()
  File "/home/runner/work/armazem-siafi-dados-2024/armazem-siafi-dados-2024/scripts/requirements.py", line 31, in check_requirements
    raise exceptions.MissingPackageError
exceptions.MissingPackageError
make: *** [Makefile:1[5](https://github.com/splor-mg/armazem-siafi-dados-2024/actions/runs/7130324547/job/19416428933#step:7:5): requirements] Error 1
Error: Process completed with exit code 2.
```

Não sei a melhor forma de lidar com isso.

**Comment by labanca** [comment]
O seguinte código se inserido no makefile parece solicionar o problema:
```
	@if [ "$(MAKECMDGOALS)" != "publish" ]; then \
		echo Checking python packages...; \
		python scripts/requirements.py; \
	fi
```

O `requirements.py` será executado em todos os targets, exceto no caso do `make publish`. 

![image](https://github.com/splor-mg/cookiecutter-datapackage/assets/7211451/0fe0b002-888d-4acf-bc66-a0ad00a58886)

![image](https://github.com/splor-mg/cookiecutter-datapackage/assets/7211451/ba13b3ab-3127-474f-957d-ac1286f06101)

![image](https://github.com/splor-mg/cookiecutter-datapackage/assets/7211451/8c90ce2d-45d1-4a5c-bdea-b6a5297f6344)
Acima vemos que o `requirements.py` não é executado no `publish`


Considerando que as versões corretas do pacotes parecem ser relevantes nos outros targets e não no `publish`, essa solução pode resolver o problema.
