### ISSUE TITLE
Criar estratégia para armazenamento de metadados gerados durante as etapas de extração e transformação

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/cookiecutter-datapackage#31]
Para atender https://github.com/splor-mg/armazem-siafi-dados/issues/9 precisamos criar uma estratégia geral de armazenamento de metadados. 

Vamos retomar a ideia de criar um arquivo json em `logs/` que é atualizado pelas etapas de extração e transformação e posteriormente inseridas no `datapackage.json` durante a etapa de build.

**Comment by labanca** [comment]
Foram criadas duas funções para facilitar a criação dos arquivos JSON e adicionar chaves a arquivos já existentes.

Primeiro, a função `write_dict_to_json(resource_name, data)` cria o arquivo `logs/resource_name.json` com o conteúdo do dicionário Python definido em `data`. 

Exemplo:
```python
#definição do dicionário
metadata_uo_setor = {
    'subject': 'uo_setor',
    'list_of_dates': ['2024-03-20', '2024-03-19', '2024-03-18'],
    'a_bool' : True,
}
write_dict_to_json('uo_setor', metadata_uo_setor)
```
Cria o arquivo arquivo 'logs/uo_setor.json':
```json
{
  "subject": "uo_setor",
  "list_of_dates": [
    "2024-03-20",
    "2024-03-19",
    "2024-03-18"
  ],
  "a_bool": true
}
```

Para adicionar um metadado chave-valor a um arquivo JSON já existente é possível utilizar a função `add_metadata_to_json(resource_name, key, value)`. 

```
add_metadata_to_json('uo_setor', 'test_add_key', 'test_value')
```

Adiciona essa nova chave ao arquivo JSON já existente para aquela `resource`.
```json
{
  "subject": "uo_setor",
  "list_of_dates": [
    "2024-03-20",
    "2024-03-19",
    "2024-03-18"
  ],
  "a_bool": true
  "test_add_key": "test_value"
}
```
Caso o arquivo JSON ainda não exista para aquela `resource` a função  `add_metadata_to_json()` também criará o arquivo:

```python
add_metadata_to_json('execucao', 'exec_key', 'exec_value')
```

```json
{
  "exec_key": "exec_value"
}
```

Durante a fase de `build` para cada `resource` definida nessa etapa, o arquivo JSON correspondente será procurado e adicionado à propriedade `metadata` do arquivo `datapackage.json` para aquela `resource`.

```json
{
"name": "obz-dados",
  "resources": [
      "name": "uo_setor",
      "type": "table",
      "path": "data-raw/uo_setor.xlsx",
      "scheme": "file",
      "format": "xlsx",
      "mediatype": "application/vnd.ms-excel",
      "encoding": "utf-8",
      "hash": "sha256:7a854572648bab3b17e507ed756bcaa1313c0ad003b71b6640d30e63e3659697",
      "bytes": 19176,
      "fields": 3,
      "rows": 59,
      "schema": {
        "fields": [
          {
            "name": "UO_COD",
            "type": "integer"
          },
          {
            "name": "UO_Sigla",
            "type": "string"
          },
          {
            "name": "Setor",
            "type": "string"
          }
        ]
      },
      "metadata": {
        "subject": "uo_setor",
        "list_of_dates": [
          "2024-03-20",
          "2024-03-19",
          "2024-03-18"
        ],
        "a_bool": true,
        "test_add_key": "test_value"
      }
    ]
}
```
